version: '2' # required to adjust maintainability checks

checks:
 method-lines:
  enabled: true
  config:
   threshold: 100

exclude_patterns:
 - 'config/'
 - 'db/'
 - 'dist/'
 - 'features/'
 - '**/node_modules/'
 - 'script/'
 - '**/spec/'
 - '**/test/'
 - '**/tests/'
 - 'Tests/'
 - '**/vendor/'
 - '**/*_test.go'
 - '**/*.d.ts'
